spring.application.name=offboarding

# Database URL - format is jdbc:mysql://<host>:<port>/<database_name>
spring.datasource.url=jdbc:mysql://localhost:3306/offboarding

# MySQL Credentials
spring.datasource.username=root
spring.datasource.password=myroot

# MySQL Driver Class (Optional in newer Spring Boot versions as it's auto-detected)
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

security.jwt.private-key=classpath:keys/private.pem
security.jwt.public-key=classpath:keys/public.pem
# 1h in millisecond
security.jwt.expiration-time=3600000

logging.level.mx.izzi.off_bording_api=DEBUG
logging.level.org.springframework.security=DEBUG
logging.level.org.hibernate.SQL=DEBUG

spring.jpa.properties.hibernate.format_sql=true
